name: semantic-release

on:
  push:
    branches:
      - main  # Change to 'main' if that's your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Fix typo in the secret name
        run: |
          git push --dry-run --no-verify https://${{ secrets.GITHUB_TOKEN }}@github.com/anni20211/semantic-release HEAD:main  # Change 'master' to 'main' if needed
          npx semantic-release
